### ISSUE TITLE
Training 

### ISSUE THREAD

**Issue by SayJMC** [ubamba98/Brain-Segmentation#1]
Hi,
I am trying to train using your codes for small basal ganglia regions using my dataset and trying to replicate what you did.
For the moment, I use exactly as you did using 6 subjects for training and 1 subject for validation. 
But I am unable to succeed. My final prediction image is very similar to the input T1 brain with some tiny contrast modification. 
I tried using model_thresholding() as well as model(). 
I do not change the model. Should I? 

Can you advise please?

Regards,
JMC

**Comment by SayJMC** [comment]
Could you respond please?

**Comment by ubamba98** [comment]
Hey sorry for late reply, I think for Basal ganglia you should use model() also does your dataset have FLAIR and T2 as well or just T1? Also could you share true labels and prediction values?
